### ISSUE TITLE
Consider improving the translator export-system design to solve potential updating-related issues

### ISSUE THREAD

**Issue by zstars** [porduna/appcomposer#71]
According to the intended first design of the translate export system, the Composer hosts the Gadget Spec and the message Bundles.

However, the Composer GETs the original Gadget Spec before every view, and dynamically injects Locales to the Bundles. The default locale is respected, and simply links to the original. 

This way, if the original author updates the application (and the default locale), then the changes take effect immediately, without any change to the translated versions of the apps. 

However, this has some potential issues:

- Workload and Latency issues: External GETs and dynamic generation are required.

- If the original author adds a translation for a specific language, or modifies a translation for a specific language, these changes wouldn't take effect on the translated apps.

- If the original author removes some variables from a translation for a specific language, again, the translated apps are not updated.

**Comment by porduna** [comment]
System changed completely
