### ISSUE TITLE
Translator: Improve / Implement translate suggestions system.

### ISSUE THREAD

**Issue by zstars** [porduna/appcomposer#87]
As of now, no real "suggestions" system is implemented.

We should consider alternatives for implementing it. Some non-extensive list of random ideas:

- Using the closest Locale. For instance, DEFAULT group when translating 10-14.
- Looking up the translation in some external translation service (such as Google's).
- Letting the user choose how to provide these advices or to provide both.

**Comment by porduna** [comment]
Implemented
